version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    nodejs: "18"
sphinx:
  configuration: docs/source/conf.py
conda:
  environment: docs/environment.yml
python:
  install:
    # install jupyterlab itself
    - method: pip
      path: .
