enableImmutableInstalls: false
enableInlineBuilds: false
enableTelemetry: false
nodeLinker: node-modules
packageExtensions:
  "@nrwl/devkit@^15":
    peerDependencies:
      typescript: "^3 || ^4 || ^5"
  "@lerna/legacy-package-management@^6.6.0":
    peerDependencies:
      nx: ">= 14.1 <= 16"
      typescript: "^3 || ^4 || ^5"
yarnPath: ./jupyterlab/staging/yarn.js
