name: Check internationalization changes

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  pull-requests: write

jobs:

  check_i18n:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-i18n-${{ hashFiles('setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-i18n-
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install jupyterlab-translate~=1.0

      - name: Compute hash
        id: i18nHash
        run: |
          set -eux
          expected=$(cat i18n.lock || true)
          # The script is quite verbose; tail is catching only the last line with the hexdigest
          actual=$(python scripts/i18n_check.py 2>/dev/null | tail -n1)

          if [[ "$expected" != "$actual" ]]; then
            echo "::set-output name=i18n::false"
          else
            echo "::set-output name=i18n::true"
          fi

      - name: Comment on PR with benchmark report
        uses: actions/github-script@v4
        env:
          I18N_RESULT: ${{ steps.i18nHash.outputs.i18n }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Source https://github.com/actions/github-script/actions/runs/187348077/workflow
          script: |
            const { I18N_RESULT } = process.env
            const header = "### Internationalization test";
            const successMsg = ":tada: Translation strings have not changed :heavy_check_mark:";
            const errorMsg = ":warning: Translatable strings have been modified :exclamation:\nThis is acceptable only for major and minor versions.";
            const message = I18N_RESULT === 'true' ? successMsg : errorMsg;

            // Get the existing comments.
            const {data: comments} = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            // Find any comment already made by the bot.
            const botComment = comments.find(comment => comment.user.id === 41898282 && body.startsWith("### Internationalization test"));

            if (botComment) {
              await github.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: [header, "", message].join("\n")
              })
            } else {
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: [header, "", message].join("\n")
              })
            }
